name: interview_project
description: Flutter project for interview
authors:
  - Bao_NH

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  camera:
  flutter:
    sdk: flutter
  path:
  path_provider:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
    # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  global_configuration: ^2.0.0-nullsafety.1
  shared_preferences: ^2.0.6
  rxdart: ^0.26.0
  provider: ^5.0.0
  easy_localization: ^3.0.0
  flutter_spinkit: ^5.0.0
  #  TODO: Beta
  flutter_launcher_icons: ^0.9.0
  #  TODO: Beta
  connectivity_macos: ^0.2.0
  connectivity: ^3.0.6
  permission_handler: ^8.0.0+2
  device_info: ^2.0.2
  back_button_interceptor: ^5.0.0
  cached_network_image: ^3.0.0
  get_it: ^7.1.3
  url_launcher: ^6.0.6
  flutter_inappwebview: ^5.3.2
  dropdown_search: ^0.6.1
  dio: ^4.0.0
  flutter_svg: ^0.22.0
  image_gallery_saver: ^1.6.9
  image_picker: ^0.7.5+3
  shimmer: ^2.0.0

  # GraphQL
  graphql_flutter: ^5.0.0-nullsafety.5
  #  TODO: beta
  artemis: ^7.0.0-beta.13
  build_runner: ^2.0.4
  json_serializable: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "lib/resources/assets/images/ic_super.png"
  image_path_android: "lib/resources/assets/images/ic_super.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/resources/assets/images/ic_super.png
    - lib/resources/assets/images/bg_welcome.png
    - lib/resources/assets/images/ic_splash_app.png
    - lib/resources/assets/images/ico_congratulate_dialog.svg
    - lib/resources/assets/images/ic_logo_app.png
    - lib/resources/assets/images/no_image.png
    - lib/resources/assets/images/no_image_available.png
    - lib/resources/assets/images/ico_start_sad.svg

    # Image of Navigation Bottom
    - lib/resources/assets/bottom/settings.svg
    - lib/resources/assets/bottom/store.svg

    # Load file Json Multi Language
    - lib/resources/translations/en-US.json
    - lib/resources/translations/vi-VN.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Quicksand #https://fonts.google.com/specimen/Quicksand?query=quicksand#standard-styles
      fonts:
        - asset: lib/resources/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: lib/resources/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: lib/resources/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: lib/resources/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: lib/resources/fonts/Quicksand-SemiBold.ttf
          weight: 600
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
